version: '3.8'

services:
  postgres:
    image: postgres
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "timezone=Asia/Shanghai"]
